#ifndef WOLF_CONFIG_H
#define WOLF_CONFIG_H

#define ETHERNET
#define LINK_MTU 1514

#define MAX_TCPSOCKETS 3
#define MAX_UDPSOCKETS 1
#define RXBUF_SIZE LINK_MTU * 4
#define TXBUF_SIZE LINK_MTU * 3

#define MAX_NEIGHBORS 4

#define WOLFIP_ENABLE_LOOPBACK 1
#define WOLFIP_MAX_INTERFACES 4
#define WOLFIP_NOSTATIC 1

#endif
