#ifndef WOLF_CONFIG_H
#define WOLF_CONFIG_H

#define ETHERNET

#ifndef LINK_MTU
#define LINK_MTU 1514
#endif

#ifdef CONFIG_MAX_TCPSOCKETS
#define MAX_TCPSOCKETS CONFIG_MAX_TCPSOCKETS
#else
#define MAX_TCPSOCKETS 4
#endif

#ifdef CONFIG_MAX_UDPSOCKETS
#define MAX_UDPSOCKETS CONFIG_MAX_UDPSOCKETS
#else
#define MAX_UDPSOCKETS 2
#endif

#ifdef CONFIG_MAX_ICMPSOCKETS
#define MAX_ICMPSOCKETS CONFIG_MAX_ICMPSOCKETS
#else
#define MAX_ICMPSOCKETS 1
#endif

#ifdef CONFIG_RXBUF_SIZE
#define RXBUF_SIZE CONFIG_RXBUF_SIZE
#else
#define RXBUF_SIZE 1024
#endif

#ifdef CONFIG_TXBUF_SIZE
#define TXBUF_SIZE CONFIG_TXBUF_SIZE
#else
#define TXBUF_SIZE 1024
#endif

#define CONFIG_IPFILTER 0

#ifdef CONFIG_WOLFIP_RAWSOCKETS
#define WOLFIP_RAWSOCKETS CONFIG_WOLFIP_RAWSOCKETS
#else
#define WOLFIP_RAWSOCKETS 0
#endif

#ifdef CONFIG_WOLFIP_MAX_RAWSOCKETS
#define WOLFIP_MAX_RAWSOCKETS CONFIG_WOLFIP_MAX_RAWSOCKETS
#else
#define WOLFIP_MAX_RAWSOCKETS 2
#endif

#ifdef CONFIG_WOLFIP_PACKET_SOCKETS
#define WOLFIP_PACKET_SOCKETS CONFIG_WOLFIP_PACKET_SOCKETS
#else
#define WOLFIP_PACKET_SOCKETS 0
#endif

#ifdef CONFIG_WOLFIP_MAX_PACKETSOCKETS
#define WOLFIP_MAX_PACKETSOCKETS CONFIG_WOLFIP_MAX_PACKETSOCKETS
#else
#define WOLFIP_MAX_PACKETSOCKETS 2
#endif

#ifdef CONFIG_IP_MULTICAST
#define IP_MULTICAST CONFIG_IP_MULTICAST
#endif

#ifdef CONFIG_WOLFIP_UDP_MCAST_MEMBERSHIPS
#define WOLFIP_UDP_MCAST_MEMBERSHIPS CONFIG_WOLFIP_UDP_MCAST_MEMBERSHIPS
#endif

#ifdef CONFIG_MAX_NEIGHBORS
#define MAX_NEIGHBORS CONFIG_MAX_NEIGHBORS
#else
#define MAX_NEIGHBORS 4
#endif

#ifdef CONFIG_LOOPBACK
#define WOLFIP_ENABLE_LOOPBACK CONFIG_LOOPBACK
#else
#define WOLFIP_ENABLE_LOOPBACK 1
#endif

#ifdef CONFIG_IP_FORWARD
#define WOLFIP_ENABLE_FORWARDING CONFIG_IP_FORWARD
#else
#define WOLFIP_ENABLE_FORWARDING 0
#endif


#ifdef CONFIG_WOLFIP_MAX_INTERFACES
#define WOLFIP_MAX_INTERFACES CONFIG_WOLFIP_MAX_INTERFACES
#else
#define WOLFIP_MAX_INTERFACES 2
#endif

#ifdef CONFIG_HEAP_SEGMENT_GRANULARITY
#define HEAP_SEGMENT_GRANULARITY CONFIG_HEAP_SEGMENT_GRANULARITY
#else
#define HEAP_SEGMENT_GRANULARITY 4096
#endif

#ifdef CONFIG_HEAP_SEGMENT_MIN_SIZE
#define HEAP_SEGMENT_MIN_SIZE CONFIG_HEAP_SEGMENT_MIN_SIZE
#else
#define HEAP_SEGMENT_MIN_SIZE 8192
#endif

#ifdef CONFIG_STM32_HW_HASH
#define STM32_HW_HASH CONFIG_STM32_HW_HASH
#else
#define STM32_HW_HASH 0
#endif

#ifdef CONFIG_STM32_HW_AES
#define STM32_HW_AES CONFIG_STM32_HW_AES
#else
#define STM32_HW_AES 0
#endif

#ifdef CONFIG_STM32_HW_PKA
#define STM32_HW_PKA CONFIG_STM32_HW_PKA
#else
#define STM32_HW_PKA 0
#endif

#define WOLFIP_NOSTATIC 1

#if WOLFIP_ENABLE_LOOPBACK && WOLFIP_MAX_INTERFACES < 2
#error "WOLFIP_ENABLE_LOOPBACK requires WOLFIP_MAX_INTERFACES > 1"
#endif

#endif
